=== lerwine/C195/Scheduler/resources/scheduler/StaticAddresses.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" targetNamespace="urn:Erwine.Leonard.T:C195:StaticAddresses.xsd" xmlns:a="urn:Erwine.Leonard.T:C195:StaticAddresses.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
    <xs:simpleType name="ZoneId">
        <xs:restriction base="xs:string">
            <xs:pattern value="^[^/\s]+(/[^/\s]+)?$" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="addressType">
        <xs:attribute name="key" type="xs:string" use="required" />
        <xs:attribute name="address1" type="xs:string" use="required" />
        <xs:attribute name="address2" type="xs:string" use="required" />
        <xs:attribute name="postalCode" type="xs:string" use="required" />
        <xs:attribute name="phone" type="xs:string" use="required" />
        <xs:attribute name="mainOffice" use="required" type="xs:boolean" use="required" />
    </xs:complexType>
    <xs:complexType name="cityType">
        <xs:attribute name="key" type="xs_string" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="^[^a-z]$" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="zoneId" type="a:ZoneId" use="required" />
        <xs:sequence>
            <xs:element name="address" type="a:addressType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="countryType">
        <xs:attribute name="languageTag" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="^(e[ns]|de|hi)-[A-Z]{2}$" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="defaultZoneId" type="a:ZoneId" use="required" />
        <xs:sequence>
            <xs:element name="city" type="a:cityType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:element name="definitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" type="a:countryType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lerwine/C195/Scheduler/resources/scheduler/StaticAddresses.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:a="urn:Erwine.Leonard.T:C195:StaticAddresses.xsd"
               xsi:schemaLocation="urn:Erwine.Leonard.T:C195:StaticAddresses.xsd StaticAddresses.xsd">
    <a:country languageTag="en-US">
        <a:city name="Phoenix" zoneId="US/Mountain">
            <a:address name="Phoenix Main Office" address1="127 N 2nd St" address2="" postalCode="85004" phone="(602) 440-1132" satelliteOffice="false" />
        </a:city>
        <a:city name="New York" zoneId="US/Eastern">
            <a:address name="New York Main Office" address1="405 Lexington Ave" address2="MS 4428" postalCode="10174" phone="(212) 447-1836" satelliteOffice="false" />
        </a:city>
    </a:country>
    <a:country languageTag="es-GT">
        <a:city name="Guatemala City" zoneId="America/Guatemala">
            <a:address name="Guatemala Satellite Office" address1="15 Calle" address2="" postalCode="" phone="+502 6854 2872" satelliteOffice="true" />
        </a:city>
    </a:country>
    <a:country languageTag="en-GB">
        <a:city name="London" zoneId="GB">
            <a:address name="London Main Office" address1="10 Upper Bank Street" address2="Suite 3210" postalCode="E14 5NP" phone="+44 7825 278103" satelliteOffice="false" />
        </a:city>
    </a:country>
    <a:country languageTag="de-DE">
        <a:city name="Berlin" zoneId="CET">
            <a:address name="Berlin Satellite Office" address1="Alexanderpl. 5-7" address2="" postalCode="10178" phone="+49 30 13572462" satelliteOffice="true" />
        </a:city>
    </a:country>
    <a:country languageTag="hi-IN">
        <a:city name="Mumbai" zoneId="Asia/Kolkata">
            <a:address name="Mumbai Satellite Office" address1="Road No.28b Sion East" address2="Sion Mumbai" postalCode="400022" phone="+91 22 2502 2348" satelliteOffice="true" />
        </a:city>
    </a:country>
</a:definitions>
