=== lerwine/C195/Scheduler/resources/scheduler/ZoneIdMap.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" targetNamespace="urn:Erwine.Leonard.T:C195:ZoneIdMap.xsd" xmlns:m="urn:Erwine.Leonard.T:C195:ZoneIdMap.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:simpleType name="ZoneId">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^/\s]+(/[^/\s]+){0,2}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Key">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]{2}" />
            <xs:minLength value="2" />
            <xs:maxLength value="2" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="keyValuePair">
        <xs:attribute name="key" type="m:Key" use="required" />
        <xs:attribute name="value" type="m:ZoneId" use="required" />
    </xs:complexType>
    <xs:element name="mappings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" type="m:keyValuePair" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:key name="entryKey">
            <xs:selector xpath="./m:entry" />
            <xs:field xpath="@key" />
        </xs:key>
        <xs:unique name="zoneIdValue">
            <xs:selector xpath="./m:entry" />
            <xs:field xpath="@value" />
        </xs:unique>
    </xs:element>
</xs:schema>

=== lerwine/C195/Scheduler/resources/scheduler/ZoneIdMap.xml
<m:mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="urn:Erwine.Leonard.T:C195:ZoneIdMap.xsd"
            xsi:schemaLocation="urn:Erwine.Leonard.T:C195:ZoneIdMap.xsd ZoneIdMap.xsd">
    <m:entry key="AA" value="America" />
    <m:entry key="AC" value="Africa" />
    <m:entry key="AD" value="Europe/Andorra" />
    <m:entry key="AE" value="Asia/Dubai" />
    <m:entry key="AF" value="Asia/Kabul" />
    <m:entry key="AI" value="Asia" />
    <m:entry key="AL" value="Europe/Tirane" />
    <m:entry key="AM" value="Asia/Yerevan" />
    <m:entry key="AN" value="Atlantic" />
    <m:entry key="AQ" value="Antarctica" />
    <m:entry key="AR" value="America/Argentina" />
    <m:entry key="AS" value="Pacific/Pago_Pago" />
    <m:entry key="AT" value="Europe/Vienna" />
    <m:entry key="AU" value="Australia" />
    <m:entry key="AX" value="Arctic/Longyearbyen" />
    <m:entry key="AZ" value="Asia/Baku" />
    <m:entry key="Aa" value="Australia/Adelaide" />
    <m:entry key="Ab" value="America/Argentina/Buenos_Aires" />
    <m:entry key="Ac" value="Antarctica/Casey" />
    <m:entry key="Ad" value="Australia/Darwin" />
    <m:entry key="Ae" value="Australia/Eucla" />
    <m:entry key="Ah" value="Australia/Hobart" />
    <m:entry key="Aj" value="America/Argentina/Jujuy" />
    <m:entry key="Al" value="America/Argentina/La_Rioja" />
    <m:entry key="Am" value="America/Argentina/Mendoza" />
    <m:entry key="An" value="Antarctica/Mawson" />
    <m:entry key="Ap" value="Antarctica/Palmer" />
    <m:entry key="Ar" value="America/Argentina/Rio_Gallegos" />
    <m:entry key="As" value="America/Argentina/San_Luis" />
    <m:entry key="At" value="Antarctica/Troll" />
    <m:entry key="Au" value="America/Argentina/Ushuaia" />
    <m:entry key="Av" value="Antarctica/Vostok" />
    <m:entry key="Aw" value="Antarctica/Syowa" />
    <m:entry key="Ay" value="Australia/Sydney" />
    <m:entry key="aB" value="Australia/Brisbane" />
    <m:entry key="ab" value="Australia/Broken_Hill" />
    <m:entry key="aC" value="America/Argentina/Catamarca" />
    <m:entry key="ac" value="America/Argentina/Cordoba" />
    <m:entry key="aD" value="Antarctica/Davis" />
    <m:entry key="ad" value="Antarctica/DumontDUrville" />
    <m:entry key="aL" value="Australia/Lindeman" />
    <m:entry key="al" value="Australia/Lord_Howe" />
    <m:entry key="am" value="Antarctica/Macquarie" />
    <m:entry key="aM" value="Australia/Melbourne" />
    <m:entry key="aP" value="Australia/Perth" />
    <m:entry key="aR" value="Antarctica/Rothera" />
    <m:entry key="as" value="America/Argentina/Salta" />
    <m:entry key="aS" value="America/Argentina/San_Juan" />
    <m:entry key="aT" value="America/Argentina/Tucuman" />
    <m:entry key="BB" value="America/Barbados" />
    <m:entry key="BD" value="Asia/Dhaka" />
    <m:entry key="BE" value="Europe/Brussels" />
    <m:entry key="BG" value="Europe/Sofia" />
    <m:entry key="BM" value="Atlantic/Bermuda" />
    <m:entry key="BN" value="Asia/Brunei" />
    <m:entry key="BO" value="America/La_Paz" />
    <m:entry key="BR" value="Brazil/East" />
    <m:entry key="BS" value="America/Nassau" />
    <m:entry key="BT" value="Asia/Thimphu" />
    <m:entry key="BY" value="Europe/Minsk" />
    <m:entry key="BZ" value="America/Belize" />
    <m:entry key="Ba" value="America/Araguaina" />
    <m:entry key="bA" value="Brazil/Acre" />
    <m:entry key="Bb" value="America/Bahia" />
    <m:entry key="bB" value="America/Belem" />
    <m:entry key="bb" value="America/Boa_Vista" />
    <m:entry key="Bc" value="America/Campo_Grande" />
    <m:entry key="bC" value="America/Cuiaba" />
    <m:entry key="Be" value="America/Eirunepe" />
    <m:entry key="Bf" value="America/Fortaleza" />
    <m:entry key="Bm" value="America/Maceio" />
    <m:entry key="bM" value="America/Manaus" />
    <m:entry key="Bn" value="America/Noronha" />
    <m:entry key="bN" value="Brazil/DeNoronha" />
    <m:entry key="Bp" value="America/Porto_Velho" />
    <m:entry key="Br" value="America/Recife" />
    <m:entry key="bR" value="America/Rio_Branco" />
    <m:entry key="Bs" value="America/Santarem" />
    <m:entry key="bS" value="America/Sao_Paulo" />
    <m:entry key="Bw" value="Brazil/West" />
    <m:entry key="CC" value="Indian/Cocos" />
    <m:entry key="CA" value="America/Atikokan" />
    <m:entry key="CH" value="Europe/Zurich" />
    <m:entry key="CI" value="Africa/Abidjan" />
    <m:entry key="CK" value="Pacific/Rarotonga" />
    <m:entry key="CN" value="Canada/Eastern" />
    <m:entry key="CO" value="America/Bogota" />
    <m:entry key="CR" value="America/Costa_Rica" />
    <m:entry key="CU" value="America/Havana" />
    <m:entry key="CV" value="Atlantic/Cape_Verde" />
    <m:entry key="CW" value="America/Curacao" />
    <m:entry key="CX" value="Indian/Christmas" />
    <m:entry key="CZ" value="Europe/Prague" />
    <m:entry key="Ca" value="Canada/Atlantic" />
    <m:entry key="ca" value="Canada/Saskatchewan" />
    <m:entry key="Cb" value="America/Blanc-Sablon" />
    <m:entry key="Cc" value="America/Cambridge_Bay" />
    <m:entry key="cC" value="America/Creston" />
    <m:entry key="cc" value="Canada/Central" />
    <m:entry key="Cd" value="America/Dawson" />
    <m:entry key="cD" value="America/Dawson_Creek" />
    <m:entry key="Ce" value="Pacific/Easter" />
    <m:entry key="cE" value="America/Edmonton" />
    <m:entry key="ce" value="Chile/EasterIsland" />
    <m:entry key="Cf" value="Asia/Famagusta" />
    <m:entry key="cF" value="America/Fort_Nelson" />
    <m:entry key="Cg" value="America/Glace_Bay" />
    <m:entry key="cG" value="America/Goose_Bay" />
    <m:entry key="Ch" value="America/Halifax" />
    <m:entry key="cH" value="Chile/Continental" />
    <m:entry key="Ci" value="America/Inuvik" />
    <m:entry key="cI" value="America/Iqaluit" />
    <m:entry key="Cm" value="America/Moncton" />
    <m:entry key="cM" value="Canada/Mountain" />
    <m:entry key="Cn" value="Asia/Nicosia" />
    <m:entry key="cN" value="America/Nipigon" />
    <m:entry key="cn" value="Canada/Newfoundland" />
    <m:entry key="Cp" value="America/Pangnirtung" />
    <m:entry key="cP" value="America/Punta_Arenas" />
    <m:entry key="cp" value="Canada/Pacific" />
    <m:entry key="Cr" value="America/Rainy_River" />
    <m:entry key="cR" value="America/Rankin_Inlet" />
    <m:entry key="cr" value="America/Regina" />
    <m:entry key="ct" value="America/Resolute" />
    <m:entry key="Cs" value="America/Santiago" />
    <m:entry key="cS" value="Asia/Shanghai" />
    <m:entry key="cs" value="America/St_Johns" />
    <m:entry key="Ct" value="America/Thunder_Bay" />
    <m:entry key="cT" value="America/Toronto" />
    <m:entry key="Cu" value="Asia/Urumqi" />
    <m:entry key="cU" value="Australia/Currie" />
    <m:entry key="cu" value="Cuba" />
    <m:entry key="Cv" value="America/Vancouver" />
    <m:entry key="Cw" value="America/Whitehorse" />
    <m:entry key="cW" value="America/Winnipeg" />
    <m:entry key="cw" value="America/Swift_Current" />
    <m:entry key="Cy" value="America/Yellowknife" />
    <m:entry key="cY" value="Canada/Yukon" />
    <m:entry key="DE" value="Europe/Berlin" />
    <m:entry key="DK" value="Europe/Copenhagen" />
    <m:entry key="DO" value="America/Santo_Domingo" />
    <m:entry key="DZ" value="Africa/Algiers" />
    <m:entry key="EE" value="Europe/Tallinn" />
    <m:entry key="EG" value="Africa/Cairo" />
    <m:entry key="EH" value="Africa/El_Aaiun" />
    <m:entry key="ES" value="Europe/Madrid" />
    <m:entry key="EU" value="Europe" />
    <m:entry key="Ec" value="Africa/Ceuta" />
    <m:entry key="eC" value="Atlantic/Canary" />
    <m:entry key="Eg" value="America/Guayaquil" />
    <m:entry key="eG" value="Pacific/Galapagos" />
    <m:entry key="eg" value="Egypt" />
    <m:entry key="Ei" value="Eire" />
    <m:entry key="FI" value="Europe/Helsinki" />
    <m:entry key="FJ" value="Pacific/Fiji" />
    <m:entry key="FK" value="Atlantic/Stanley" />
    <m:entry key="FM" value="Pacific/Chuuk" />
    <m:entry key="Fp" value="Pacific/Pohnpei" />
    <m:entry key="Fk" value="Pacific/Kosrae" />
    <m:entry key="FO" value="Atlantic/Faroe" />
    <m:entry key="FR" value="Europe/Paris" />
    <m:entry key="GB" value="Europe/London" />
    <m:entry key="GE" value="Asia/Tbilisi" />
    <m:entry key="GF" value="America/Cayenne" />
    <m:entry key="GH" value="Africa/Accra" />
    <m:entry key="GI" value="Europe/Gibraltar" />
    <m:entry key="GL" value="America/Nuuk" />
    <m:entry key="Gd" value="America/Danmarkshavn" />
    <m:entry key="Gs" value="America/Scoresbysund" />
    <m:entry key="Gt" value="America/Thule" />
    <m:entry key="GR" value="Europe/Athens" />
    <m:entry key="GS" value="Atlantic/South_Georgia" />
    <m:entry key="GT" value="America/Guatemala" />
    <m:entry key="GU" value="Pacific/Guam" />
    <m:entry key="GW" value="Africa/Bissau" />
    <m:entry key="GY" value="America/Guyana" />
    <m:entry key="Gw" value="Greenwich" />
    <m:entry key="HK" value="Asia/Hong_Kong" />
    <m:entry key="HN" value="America/Tegucigalpa" />
    <m:entry key="HT" value="America/Port-au-Prince" />
    <m:entry key="HU" value="Europe/Budapest" />
    <m:entry key="Hk" value="Hongkong" />
    <m:entry key="IE" value="Europe/Dublin" />
    <m:entry key="IL" value="Asia/Jerusalem" />
    <m:entry key="IK" value="Asia/Kolkata" />
    <m:entry key="IN" value="Indian" />
    <m:entry key="IO" value="Indian/Chagos" />
    <m:entry key="IQ" value="Asia/Baghdad" />
    <m:entry key="IR" value="Asia/Tehran" />
    <m:entry key="IS" value="Atlantic/Reykjavik" />
    <m:entry key="IT" value="Europe/Rome" />
    <m:entry key="ID" value="Asia/Jakarta" />
    <m:entry key="Ic" value="Iceland" />
    <m:entry key="Im" value="Asia/Makassar" />
    <m:entry key="Ip" value="Asia/Pontianak" />
    <m:entry key="iJ" value="Asia/Jayapura" />
    <m:entry key="Ir" value="Iran" />
    <m:entry key="Is" value="Israel" />
